(()=>{
'use strict';
const API='https://ydaeukhqwishlrjyfktk.supabase.co/functions/v1/ag2-development';
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=n=>Number(n||0).toLocaleString();
const date=v=>v?new Date(v).toLocaleDateString(undefined,{year:'numeric',month:'short',day:'numeric'}):'—';
let feed={posts:[],comments:[],log:null};
const statusLabel={draft:'Draft',planned:'Planned',currently_in_development:'Currently in development',ready:'Ready',released:'Released',archived:'Archived'};
async function call(action,payload={}){const r=await fetch(API,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action,...payload})});const j=await r.json().catch(()=>({ok:false,error:'INVALID_RESPONSE'}));if(!r.ok||!j.ok)throw new Error(j.error||`HTTP_${r.status}`);return j}
function commentsFor(id){return feed.comments.filter(c=>c.post_id===id)}
function media(p){return p.image_urls?.[0]?`<div class="post-media"><img src="${esc(p.image_urls[0])}" alt="${esc(p.title)}" loading="lazy"></div>`:'<div class="post-media empty-media">AG2 DEVELOPMENT MEDIA</div>'}
function chips(p){return `<div class="post-top"><span class="status-chip ${esc(p.status)}">${esc(statusLabel[p.status]||p.status)}</span><span class="kind-chip">${esc(p.kind.replace('_',' '))}</span>${p.version?`<span class="post-version">${esc(p.version)}</span>`:''}</div>`}
function commentsBlock(p){if(!p.comment_enabled)return'';const list=commentsFor(p.id),tpl=$('#commentTemplate').content.cloneNode(true),wrap=document.createElement('div');wrap.appendChild(tpl);const root=wrap.firstElementChild;root.querySelector('[data-comment-count]').textContent=`${list.length} comment${list.length===1?'':'s'}`;const box=root.querySelector('[data-comments]');box.innerHTML=list.length?list.map(c=>`<article class="comment"><strong>${esc(c.display_name)}</strong><time>${esc(date(c.created_at))}</time><p>${esc(c.body)}</p></article>`).join(''):'<div class="comment-status">No comments yet. Start the discussion.</div>';const form=root.querySelector('[data-comment-form]');form.dataset.postId=p.id;return root.outerHTML}
function postCard(p,featured=false){return `<article class="dev-post${featured?' featured':''}" data-post-id="${p.id}">${featured?media(p):''}<div class="post-body">${chips(p)}<h3>${esc(p.title)}</h3>${p.summary?`<p class="post-summary">${esc(p.summary)}</p>`:''}${p.body?`<div class="post-content">${esc(p.body)}</div>`:''}<div class="post-meta">${p.target_date?`<span>Target ${esc(date(p.target_date))}</span>`:''}<span>Updated ${esc(date(p.updated_at||p.published_at))}</span></div>${commentsBlock(p)}</div>${!featured&&p.image_urls?.[0]?media(p):''}</article>`}
function renderLog(){const el=$('#diagnosticSnapshot'),l=feed.log;if(!l){el.className='diag-empty';el.textContent='No public diagnostic snapshot has been published yet.';return}el.className='diag-grid';el.innerHTML=`<div class="diag-score"><span>Build health</span><strong>${esc(l.health_score)}</strong><small>${esc(l.health_label||'Analyzed')}</small></div><div class="diag-stat"><span>Critical</span><strong>${fmt(l.critical_count)}</strong><small>high-risk</small></div><div class="diag-stat"><span>Errors</span><strong>${fmt(l.error_count)}</strong><small>detected</small></div><div class="diag-stat"><span>Warnings</span><strong>${fmt(l.warning_count)}</strong><small>non-fatal</small></div><div class="diag-stat"><span>Groups</span><strong>${fmt(l.unique_groups)}</strong><small>deduplicated</small></div><div class="diag-stat"><span>Events</span><strong>${fmt(l.parsed_events)}</strong><small>parsed</small></div><div class="diag-meta"><span>Report ${esc(l.report_id)}</span><span>Build ${esc(l.build||'Unassigned')}</span><span>Top subsystem ${esc(l.top_subsystem||'—')}</span><span>Published ${esc(date(l.published_at))}</span></div>`}
function render(){renderLog();const active=feed.posts.filter(p=>p.kind==='next_update'&&p.status==='currently_in_development');$('#developmentFeed').innerHTML=active.length?active.map(p=>postCard(p,true)).join(''):'<div class="empty">No active development post yet.</div>';const next=feed.posts.filter(p=>p.kind==='next_update'&&['planned','ready'].includes(p.status));$('#nextUpdateFeed').innerHTML=next.length?next.map(p=>postCard(p)).join(''):'<div class="empty">No next update has been published yet.</div>';const rel=feed.posts.filter(p=>p.kind==='new_update'||(p.kind==='next_update'&&p.status==='released'));$('#newUpdateFeed').innerHTML=rel.length?rel.map(p=>postCard(p)).join(''):'<div class="empty">No release post has been published yet.</div>';const ann=feed.posts.filter(p=>p.kind==='announcement');$('#announcementFeed').innerHTML=ann.length?ann.map(p=>`<article class="notice">${chips(p)}<h3>${esc(p.title)}</h3><p>${esc(p.summary||p.body)}</p></article>`).join(''):'<div class="empty">No announcements.</div>';const ch=feed.posts.filter(p=>p.kind==='changelog');$('#changelogFeed').innerHTML=ch.length?ch.map(p=>`<article class="change">${p.version?`<span class="post-version">${esc(p.version)}</span>`:''}<h3>${esc(p.title)}</h3><p>${esc(p.summary||p.body)}</p></article>`).join(''):'<div class="empty">No changelog entries.</div>';const hs=$('#heroStatus');const primary=active[0]||next[0]||rel[0];hs.innerHTML=`<span>LIVE PROJECT STATUS</span><strong>${esc(primary?statusLabel[primary.status]:'Development feed online')}</strong><small>${primary?esc(primary.version||primary.title):'Synced from DLAVIE DEV Console'}</small>`;bindComments()}
function bindComments(){$$('[data-comment-form]').forEach(f=>f.addEventListener('submit',async e=>{e.preventDefault();const btn=f.querySelector('button'),name=f.elements.name.value.trim(),body=f.elements.body.value.trim();if(!name||!body)return;btn.disabled=true;btn.textContent='Posting…';try{const j=await call('submit_comment',{post_id:f.dataset.postId,display_name:name,body});feed.comments.push(j.comment);f.elements.body.value='';render()}catch(err){btn.disabled=false;btn.textContent='Post comment';alert(err.message==='RATE_LIMIT'?'Too many comments. Please try again later.':'Could not post comment.')}}))}
async function load(){document.body.classList.add('loading');try{feed=await call('public_feed');render()}catch(e){console.error(e);$('#heroStatus').innerHTML='<span>DEVELOPMENT FEED</span><strong>Temporarily unavailable</strong><small>Please try again later.</small>'}finally{document.body.classList.remove('loading')}}
$('#menuBtn')?.addEventListener('click',()=>$('#mobileNav').classList.toggle('open'));$('#mobileNav')?.addEventListener('click',()=>$('#mobileNav').classList.remove('open'));load();
})();