(()=>{
'use strict';
const API='https://ydaeukhqwishlrjyfktk.supabase.co/functions/v1/ag2-development';
const SB_URL='https://ydaeukhqwishlrjyfktk.supabase.co';
const SB_KEY='sb_publishable_XNXU6SVeM-D477Ymy1ORsw_4hCHOll9';
const TOKEN_KEY='ag2.dev.backend.token.v1';
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=n=>Number(n||0).toLocaleString();
let data={posts:[],comments:[],logs:[]},active=null,images=[];
const statusLabel={draft:'Draft',planned:'Planned',currently_in_development:'In development',ready:'Ready',released:'Released',archived:'Archived'};
const kindLabel={announcement:'Announcement',changelog:'Changelog',next_update:'Next update',new_update:'New update'};
function token(){return localStorage.getItem(TOKEN_KEY)||''}
function notify(m){window.AG2_DEV_TOAST?window.AG2_DEV_TOAST(m):console.info(m)}
async function api(action,payload={}){const r=await fetch(API,{method:'POST',headers:{'content-type':'application/json','x-dlavie-console-token':token()},body:JSON.stringify({action,...payload})});const j=await r.json().catch(()=>({ok:false,error:'INVALID_RESPONSE'}));if(!r.ok||!j.ok)throw new Error(j.error||`HTTP_${r.status}`);return j}
function inject(){if($('[data-panel="development"]'))return;const nav=$('.side-nav');if(nav){const label=document.createElement('div');label.className='nav-section-label';label.textContent='Publishing';const b=document.createElement('button');b.className='nav-item';b.dataset.view='development';b.innerHTML='<svg viewBox="0 0 24 24"><path d="M4 6h16M4 12h10M4 18h13"/></svg><span>Development</span>';nav.append(label,b);b.addEventListener('click',()=>openView())}
 const main=$('.workspace');if(!main)return;const section=document.createElement('section');section.className='view';section.dataset.panel='development';section.innerHTML=`<div class="page-head compact"><div><p class="eyebrow">PUBLIC PROJECT HUB</p><h1>Development</h1><p class="subhead">Publish changelogs, announcements, next updates, release posts, images and the public diagnostic snapshot.</p></div><div class="head-actions"><a class="ghost devcms-public-link" href="../development/" target="_blank" rel="noopener">Open public page ↗</a><button class="ghost" id="devcmsRefresh">Refresh</button></div></div>
 <div class="devcms-panel"><div class="devcms-head"><div><span>SYNC STATUS</span><strong>Development Hub backend</strong></div><div class="devcms-status" id="devcmsStatus"><i></i><span>Checking session…</span></div></div><div class="devcms-body"><div class="devcms-sync" id="devcmsStats"></div></div></div>
 <div class="devcms-grid devcms-section-space"><article class="devcms-panel"><div class="devcms-head"><div><span>CONTENT EDITOR</span><strong id="devcmsEditorTitle">Create development post</strong></div><button class="devcms-mini-btn" id="devcmsNew">New</button></div><div class="devcms-body"><form class="devcms-form" id="devcmsForm"><div class="devcms-field"><label>Type</label><select name="kind"><option value="next_update">Next update</option><option value="new_update">New update</option><option value="changelog">Changelog</option><option value="announcement">Announcement</option></select></div><div class="devcms-field"><label>Status</label><select name="status"><option value="draft">Draft</option><option value="planned">Planned</option><option value="currently_in_development">Currently in development</option><option value="ready">Ready</option><option value="released">Released</option><option value="archived">Archived</option></select></div><div class="devcms-field full"><label>Title</label><input name="title" maxlength="160" required placeholder="Update title"></div><div class="devcms-field"><label>Version</label><input name="version" maxlength="80" placeholder="e.g. V3.7.11"></div><div class="devcms-field"><label>Target date</label><input name="target_date" type="date"></div><div class="devcms-field full"><label>Short description</label><textarea name="summary" rows="3" maxlength="500" placeholder="Short summary shown on cards"></textarea></div><div class="devcms-field full"><label>Full description / changelog</label><textarea name="body" rows="8" maxlength="20000" placeholder="Detailed development notes"></textarea></div><div class="devcms-media"><div class="devcms-field"><label>Images</label><div class="devcms-media-toolbar"><label class="devcms-mini-btn" for="devcmsImageInput">Add photo</label><input id="devcmsImageInput" type="file" accept="image/png,image/jpeg,image/webp,image/gif" multiple><span id="devcmsUploadState" class="devcms-status">Up to 12 images</span></div></div><div class="devcms-media-grid" id="devcmsMediaGrid"></div></div><div class="devcms-toggles"><label class="devcms-toggle"><input name="published" type="checkbox"> Visible on public page</label><label class="devcms-toggle"><input name="comment_enabled" type="checkbox"> Enable comments</label><label class="devcms-toggle"><input name="pinned" type="checkbox"> Pin post</label></div><div class="devcms-field"><label>Sort order</label><input name="sort_order" type="number" min="0" max="9999" value="100"></div><div class="devcms-actions"><button class="save" type="submit">Save & sync</button><button type="button" id="devcmsDuplicate">Duplicate</button><button class="danger" type="button" id="devcmsDelete">Delete</button></div></form></div></article>
 <aside class="devcms-panel"><div class="devcms-head"><div><span>PUBLISHED CONTENT</span><strong>Development posts</strong></div></div><div class="devcms-body"><div class="devcms-post-list" id="devcmsPostList"></div></div></aside></div>
 <div class="devcms-grid devcms-section-space"><article class="devcms-panel"><div class="devcms-head"><div><span>PUBLIC DIAGNOSTIC</span><strong>Latest synchronized ContentLog summary</strong></div></div><div class="devcms-body" id="devcmsLog"></div></article><article class="devcms-panel"><div class="devcms-head"><div><span>COMMENTS</span><strong>Public development discussion</strong></div></div><div class="devcms-body"><div class="devcms-comments" id="devcmsComments"></div></div></article></div>`;main.appendChild(section);bind();}
function openView(){ $$('.view').forEach(v=>v.classList.toggle('active',v.dataset.panel==='development'));$$('.nav-item').forEach(n=>n.classList.toggle('active',n.dataset.view==='development'));$('#sidebar')?.classList.remove('open');$('#sidebarScrim')?.classList.remove('show');window.scrollTo({top:0});load()}
function bind(){const f=$('#devcmsForm');f.addEventListener('submit',save);$('#devcmsNew').onclick=reset;$('#devcmsRefresh').onclick=load;$('#devcmsDelete').onclick=remove;$('#devcmsDuplicate').onclick=()=>{if(!active)return;active=null;$('#devcmsEditorTitle').textContent='Duplicate development post';f.elements.title.value+=' Copy'};$('#devcmsImageInput').addEventListener('change',e=>uploadFiles([...e.target.files]));}
async function load(){const st=$('#devcmsStatus');if(!token()){st.className='devcms-status bad';st.innerHTML='<i></i><span>Cloud session unavailable — lock and unlock console once.</span>';render();return}try{data=await api('admin_list');st.className='devcms-status';st.innerHTML='<i></i><span>Synced · public hub online</span>';render()}catch(e){st.className='devcms-status bad';st.innerHTML=`<i></i><span>${esc(e.message)}</span>`;render()}}
function render(){const stats=$('#devcmsStats');if(stats)stats.innerHTML=[['Posts',data.posts.length],['Public',data.posts.filter(p=>p.published).length],['In dev',data.posts.filter(p=>p.status==='currently_in_development').length],['Comments',data.comments.length],['Log snapshots',data.logs.length]].map(([a,b])=>`<div class="devcms-stat"><span>${a}</span><strong>${fmt(b)}</strong></div>`).join('');const list=$('#devcmsPostList');if(list)list.innerHTML=data.posts.length?data.posts.map(p=>`<article class="devcms-post${active?.id===p.id?' active':''}" data-id="${p.id}"><div><strong>${esc(p.title)}</strong><small>${esc(kindLabel[p.kind]||p.kind)} · ${esc(p.version||'No version')} · ${p.published?'Public':'Private'}</small></div><b>${esc(statusLabel[p.status]||p.status)}</b></article>`).join(''):'<div class="devcms-empty">No posts yet.</div>';$$('.devcms-post').forEach(x=>x.onclick=()=>edit(x.dataset.id));renderMedia();renderLog();renderComments()}
function renderMedia(){const g=$('#devcmsMediaGrid');if(!g)return;g.innerHTML=images.map((u,i)=>`<div class="devcms-media-item"><img src="${esc(u)}" alt="Development image"><button type="button" data-rm="${i}">×</button></div>`).join('');$$('[data-rm]',g).forEach(b=>b.onclick=()=>{images.splice(Number(b.dataset.rm),1);renderMedia()})}
function renderLog(){const l=data.logs[0],el=$('#devcmsLog');if(!el)return;if(!l){el.innerHTML='<div class="devcms-empty">Analyze a ContentLog after cloud login to publish its aggregate summary here.</div>';return}el.innerHTML=`<div class="devcms-sync"><div class="devcms-stat"><span>Health</span><strong>${l.health_score}</strong></div><div class="devcms-stat"><span>Critical</span><strong>${fmt(l.critical_count)}</strong></div><div class="devcms-stat"><span>Errors</span><strong>${fmt(l.error_count)}</strong></div><div class="devcms-stat"><span>Warnings</span><strong>${fmt(l.warning_count)}</strong></div><div class="devcms-stat"><span>Groups</span><strong>${fmt(l.unique_groups)}</strong></div></div><p style="color:#747e89;font-size:8px;margin:12px 0 0">Report ${esc(l.report_id)} · Build ${esc(l.build||'Unassigned')} · raw log content is never published.</p>`}
function renderComments(){const el=$('#devcmsComments');if(!el)return;el.innerHTML=data.comments.length?data.comments.slice(0,80).map(c=>`<article class="devcms-comment"><div class="devcms-comment-top"><div><strong>${esc(c.display_name)}</strong><small> · ${esc(c.post_title||'Post')}</small></div><small>${new Date(c.created_at).toLocaleString()}</small></div><p>${esc(c.body)}</p><div class="devcms-comment-actions"><button data-comment="${c.id}" data-status="published">Publish</button><button data-comment="${c.id}" data-status="hidden">Hide</button><button data-delete-comment="${c.id}">Delete</button></div></article>`).join(''):'<div class="devcms-empty">No public comments yet.</div>';$$('[data-comment]',el).forEach(b=>b.onclick=async()=>{await api('moderate_comment',{id:b.dataset.comment,status:b.dataset.status});notify('Comment updated.');load()});$$('[data-delete-comment]',el).forEach(b=>b.onclick=async()=>{if(!confirm('Delete this comment?'))return;await api('delete_comment',{id:b.dataset.deleteComment});notify('Comment deleted.');load()})}
function edit(id){active=data.posts.find(p=>p.id===id)||null;if(!active)return;const f=$('#devcmsForm');$('#devcmsEditorTitle').textContent='Edit development post';for(const k of ['kind','status','title','version','target_date','summary','body','sort_order'])if(f.elements[k])f.elements[k].value=active[k]??'';for(const k of ['published','comment_enabled','pinned'])f.elements[k].checked=!!active[k];images=[...(active.image_urls||[])];render()}
function reset(){active=null;images=[];const f=$('#devcmsForm');f.reset();f.elements.kind.value='next_update';f.elements.status.value='draft';f.elements.sort_order.value='100';$('#devcmsEditorTitle').textContent='Create development post';render()}
async function save(e){e.preventDefault();const f=e.currentTarget,post={kind:f.elements.kind.value,status:f.elements.status.value,title:f.elements.title.value,version:f.elements.version.value,target_date:f.elements.target_date.value||null,summary:f.elements.summary.value,body:f.elements.body.value,image_urls:images,published:f.elements.published.checked,comment_enabled:f.elements.comment_enabled.checked,pinned:f.elements.pinned.checked,sort_order:Number(f.elements.sort_order.value||100)};try{const j=await api('save_post',{id:active?.id,post});active=j.post;images=[...(j.post.image_urls||[])];notify('Development post synchronized.');await load()}catch(err){notify(`Could not save: ${err.message}`)}}
async function remove(){if(!active)return;if(!confirm(`Delete “${active.title}”?`))return;try{await api('delete_post',{id:active.id});notify('Post deleted.');reset();await load()}catch(e){notify(`Could not delete: ${e.message}`)}}
async function uploadFiles(files){files=files.filter(f=>/^image\/(png|jpeg|webp|gif)$/i.test(f.type)).slice(0,Math.max(0,12-images.length));if(!files.length)return;const state=$('#devcmsUploadState');state.textContent='Uploading…';try{const {createClient}=await import('https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm');const client=createClient(SB_URL,SB_KEY,{auth:{persistSession:false}});for(const file of files){const safe=file.name.toLowerCase().replace(/[^a-z0-9._-]+/g,'-').slice(-70),slug=(active?.slug||$('#devcmsForm').elements.title.value||'post').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,60)||'post',path=`ag2-development/${slug}/${Date.now()}-${safe}`;const s=await api('create_upload',{path,content_type:file.type});const up=await client.storage.from('dlavie-project-media').uploadToSignedUrl(s.path,s.token,file,{contentType:file.type});if(up.error)throw up.error;images.push(s.public_url)}renderMedia();state.textContent=`${images.length} image${images.length===1?'':'s'}`;notify('Development image uploaded.')}catch(e){console.error(e);state.textContent='Upload failed';notify(`Image upload failed: ${e.message}`)}finally{$('#devcmsImageInput').value=''}}
async function digest(text){const b=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(text));return[...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('')}
function sev(line){const s=line.toLowerCase();if(/fatal|force[- ]?close|crash|terminated|watchdog.*(?:terminate|kill|fatal)|out of memory/.test(s))return'CRITICAL';if(/\berror\b|exception|failed|failure|invalid|not found|missing|unknown token|cannot|could not|schema error|syntax error/.test(s))return'ERROR';if(/\bwarn(?:ing)?\b|deprecated|fallback|ignored/.test(s))return'WARNING';return'INFO'}
function cat(line){const s=line.toLowerCase();if(/watchdog|script runtime|javascript|@minecraft|typeerror|referenceerror|syntaxerror|event handler|stack trace/.test(s))return'SCRIPT';if(/animation|anim_controller|animation_controller|state machine|reload_start|animation state/.test(s))return'ANIMATION';if(/molang|unknown token|query\.|variable\.|math\./.test(s))return'MOLANG';if(/particle|billboard|emitter|particle_effect/.test(s))return'PARTICLE';if(/recipe|crafting|furnace recipe/.test(s))return'RECIPE';if(/resource pack|texture|render_controller|geometry\.|material|pbr|normal map|roughness|metalness|attachable/.test(s))return'RESOURCE PACK';if(/weapon|gun|recoil|\bads\b|ammo|chamber|attachment|projectile|laser|bipod|wall collision/.test(s))return'WEAPON';if(/block schema|block component|minecraft:block|block permutation|block definition/.test(s))return'BLOCK';return'INFO'}
function norm(line,c){return`${c}|${line.toLowerCase().replace(/\[(?:\d{2}:){2}\d{2}(?:\.\d+)?\]/g,'').replace(/:\d+\b/g,':<n>').replace(/\b\d+(?:\.\d+)?\s*ms\b/gi,'<ms>').replace(/\b\d{4,}\b/g,'<n>').replace(/\s+/g,' ').trim().slice(0,440)}`}
async function syncLog(file){if(!file||!token())return;try{const text=await file.text(),lines=text.replace(/\r/g,'').split('\n'),counts={CRITICAL:0,ERROR:0,WARNING:0,INFO:0},cats=new Map(),groups=new Set();let parsed=0;for(const line of lines){if(!line.trim())continue;parsed++;const s=sev(line),c=cat(line);counts[s]++;cats.set(c,(cats.get(c)||0)+1);if(s!=='INFO'||c!=='INFO')groups.add(norm(line,c))}const issues=counts.CRITICAL+counts.ERROR+counts.WARNING,n=Math.max(1,parsed),penalty=counts.CRITICAL*15+(counts.ERROR/n)*72+(counts.WARNING/n)*22+(groups.size/n)*18,health=Math.max(0,Math.min(100,Math.round(100-penalty))),healthLabel=health>=90?'Excellent':health>=75?'Stable':health>=55?'Needs review':health>=30?'High risk':'Critical',top=[...cats.entries()].sort((a,b)=>b[1]-a[1])[0]?.[0]||'—',hash=await digest(text),report={reportId:hash.slice(0,12).toUpperCase(),build:$('#activeBuild')?.textContent?.trim()||'UNASSIGNED',sourceName:file.name,healthScore:health,healthLabel,criticalCount:counts.CRITICAL,errorCount:counts.ERROR,warningCount:counts.WARNING,issueCount:issues,uniqueGroups:groups.size,parsedEvents:parsed,topSubsystem:top,generatedAt:new Date().toISOString(),dedupeRatio:issues?Math.round((1-groups.size/issues)*1000)/10:0,issueRate:Math.round(issues/n*1000)/10};await api('publish_log_summary',{report});notify('Public development diagnostic snapshot synchronized.');if($('[data-panel="development"].active'))load()}catch(e){console.warn('AG2 development log sync',e)}}
function bindLogSync(){const input=$('#fileInput'),drop=$('#dropZone');input?.addEventListener('change',e=>syncLog(e.target.files?.[0]));drop?.addEventListener('drop',e=>syncLog(e.dataTransfer?.files?.[0]))}
function boot(){inject();bindLogSync();}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();